import 'package:hive/hive.dart';

part 'customer.g.dart'; // This line will be generated by build_runner

@HiveType(typeId: 0) // Unique ID for this type across all your Hive models
class Customer extends HiveObject {
  @HiveField(0)
  late String name;

  @HiveField(1)
  late String phone;

  @HiveField(2)
  late String address;

  Customer({required this.name, required this.phone, required this.address});
}